# local, dev
env: "local"

log:
  # trace, debug, info, warn, error
  level: "debug"

postgres:
  conn_timout: 5s
  max_conns: 4
  min_conns: 0
  max_conn_lifetime: 60m
  max_conn_idle_time: 30m
  health_check_period: 1m

redis:
  dial_timeout: 5s
